### ISSUE TITLE
I am not able to access the LeakDB dataset from the link provided [https://goo.by/j1Gpg](https://github.com/KIOS-Research/LeakDB/issues/url) in the Repo. Please help. 

### ISSUE THREAD

**Issue by jackishappy** [KIOS-Research/LeakDB#2]

**Comment by Mariosmsk** [comment]
Hi @jackishappy, please check here: [DATASET](https://ucy-my.sharepoint.com/:f:/g/personal/mkiria01_ucy_ac_cy/Eiyah0-TL4dGqt9K4Ln5TN0BRlroASbX35p53bS7or4j5A)
